---

- hosts: all
  become: true
  tasks:


    - name: install apache2 and PHP support for ubuntu
      apt:
        name: 
        - apache2
        - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: install python for ubuntu
      apt:
        name: 
        - python
        state: latest

