---

- hosts: all
  become: true
  pre_tasks:
    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install updates (CentOS)
      tags: always
      package:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

# adding users 

- hosts: all
  become: true
  tasks:
    - name: adding user simone
      tags: always
      user:
        name: simone
        groups: root

# adding ssh key and sudoers permission to simone
    - name: add ssh key to simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC69gjok+Cm+2ABD5LJ9/dBsfHntYxYsBJAYrJKoOPAiE/jIvclA+ZApYLWMIWl8RGWyLxSLj8xDbCCqXuBpnyMEI68V23ngWVtg5lVzwKWToN0diT/dGUWi7KNNgrpLh9D/o+bH7wtWn2+ejDBwDKjN5+tFfuG15+dKUkFwc3TeaPfb4e9BfrqOq34XCCdpjKb3QgaBUL8dz7SUf/6qJRhrgi/hCXM41vEB2ZGm33L+xiuicaJzTR9ak8A8U2d+tuKzKFZ5UsEoS/nlG0u+Igb/E2zTZGyQ/7kn0h21eGULVgqkY1D9xa75Oseu31YbVkRwGr2TsJ9M2ghiQ9vKUSS+IP3JfXdK7RzTI4Hga7Hgc/oFpPuEac3wAXOMMNS3FU6GXrHtjZCD53P/FfNaK7o5Q5CqA1UtrHLcnYsNF8QH7aqsDoQ9cP7B7MMyax/NfPI+1X8AD4yMuoWpcINrNcrj1S1TUkKSwKePqWP06Jw73I5WIvGS2fVAarKH4luXVs= ansible"

    - name: add sudoers file for simone
      tags: always
      copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 and php for ubuntu web_servers
      tags: apache2,apache,ubuntu
      apt:
        name:
        - apache2
        - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for CentOS web_servers
      tags: httpd,apache,centos
      package:
        name:
        - httpd
        - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: start httpd service
      tags: apache,centos,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: change email for admin (CentOS)
      tags: centos,apache,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin tarunvickygm@gmail.com
      when: ansible_distribution == "CentOS"
      register: httpd

    - name: restating service (CentOS, httpd)
      tags: centos,apache,httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed


    - name: copy html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.2.7/terraform_1.2.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb (CentOS)
      tags: db,mariadb,centos
      dnf:
        name:
        - mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name:
        - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest

