- name: install redis (CentOS)
  tags: db,mariadb,centos
  package:
      name:
      - mariadb
      state: latest
      when: ansible_distribution == "CentOS"

- name: install mariadb (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name:
    - mariadb-server
    state: latest
    when: ansible_distribution == "Ubuntu"